#!/bin/bash

# Initialize configuration for Aspens
# This script sets up:
# - Deploys factory contracts on both chains using forge
# - Uses deterministic mock-signer keys as contract signers (Key 0 and Key 1)
# - Two chains: base-sepolia and flare-coston2 (using mock-signer keys)
# - Deploys trading contracts via factory on both chains
# - Tokens: USDC on base-sepolia, USDT0 and WC2FLR on flare-coston2
# - Markets: USDC/USDT0 and WC2FLR/USDC
# - Fetches and displays signer public keys from the Aspens Market Stack
#
# The mock-signer generates deterministic keys:
#   - Key 0: 0x88ea7374a796c6f31cbfd0f9198b0c473d5ed7ce (base chain)
#   - Key 1: 0x6176a61ec3fc1f79358ff241ee835f7143a20b69 (quote chain)
#
# Usage: ./scripts/init-config.sh
#
# Must be run from the aspens directory (not aspens/scripts)
#
# Prerequisites:
# - aspens-admin binary built (cargo build --package aspens-admin)
# - foundry/forge installed (for deploying factory contracts)
# - grpcurl installed (for fetching signer public keys)
# - Aspens Market Stack running at ASPENS_MARKET_STACK_URL
# - mock-signer running (provides the deterministic signer keys)
# - Anvil chains running on localhost:8545 and localhost:8546
# - ADMIN_PRIVKEY set in your .env file for the admin wallet
# - ASPENS_MARKET_STACK_URL set in your .env file

set -e

# Load .env file if it exists
if [[ -f .env ]]; then
    set -a
    source .env
    set +a
fi

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }
print_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# Default values
ASPENS_ADMIN="cargo run --package aspens-admin --"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --help|-h)
            echo "Usage: $0"
            echo ""
            echo "This script initializes the Aspens stack with:"
            echo "  - Deploys factory contracts on both chains"
            echo "  - Uses deterministic mock-signer keys as contract signers"
            echo "    - Base chain (Key 0): 0x88ea7374a796c6f31cbfd0f9198b0c473d5ed7ce"
            echo "    - Quote chain (Key 1): 0x6176a61ec3fc1f79358ff241ee835f7143a20b69"
            echo "  - Chains: base-sepolia, flare-coston2"
            echo "  - Deploys trading contracts via factory on both chains"
            echo "  - Tokens: USDC (base-sepolia), USDT0/WC2FLR (flare-coston2)"
            echo "  - Markets: USDC/USDT0, WC2FLR/USDC"
            echo "  - Fetches and displays signer public keys"
            echo ""
            echo "Must be run from the aspens directory: ./scripts/init-config.sh"
            echo ""
            echo "Configuration is read from .env file (ASPENS_MARKET_STACK_URL, ADMIN_PRIVKEY)"
            echo ""
            echo "Prerequisites:"
            echo "  - aspens-admin binary built"
            echo "  - foundry/forge installed"
            echo "  - grpcurl installed"
            echo "  - mock-signer running"
            echo "  - Aspens Market Stack running"
            echo "  - Anvil chains running on localhost:8545 and localhost:8546"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# ============================================================================
# Configuration - Update these values for your deployment
# ============================================================================

# Base Sepolia configuration
BASE_SEPOLIA_CHAIN_ID=84532
BASE_SEPOLIA_RPC_URL="http://localhost:8545"
BASE_SEPOLIA_EXPLORER="https://sepolia.basescan.org"
BASE_SEPOLIA_PERMIT2_ADDRESS="0x000000000022D473030F116dDEE9F6B43aC78BA3"

# Flare Coston2 configuration
FLARE_COSTON2_CHAIN_ID=114
# FLARE_COSTON2_RPC_URL="https://coston2-api.flare.network/ext/C/rpc"
FLARE_COSTON2_RPC_URL="http://localhost:8546"
FLARE_COSTON2_EXPLORER="https://coston2-explorer.flare.network"
FLARE_COSTON2_PERMIT2_ADDRESS="0xB952578f3520EE8Ea45b7914994dcf4702cEe578"

# Path to arborter directory (for reading deployment artifacts)
ARBORTER_DIR="${ARBORTER_DIR:-../arborter}"

# Token addresses
USDC_ADDRESS_BASE="0x036CbD53842c5426634e7929541eC2318f3dCF7e"    # USDC on Base Sepolia
USDT0_ADDRESS_FLARE="0xC1A5B41512496B80903D1f32d6dEa3a73212E71F"  # USDT0 on Flare Coston2
WC2FLR_ADDRESS_FLARE="0xC67DCE33D7A8efA5FfEB961899C73fe01bCe9273"  # WC2FLR on Flare Coston2

# ============================================================================
# Script execution
# ============================================================================

print_info "Initializing Aspens Market Stack configuration"
echo ""

# Use deterministic signer addresses from mock-signer
# These are the first two keys generated by the mock-signer service
# See: infra/mock-signer/README.md for details
print_step "Step 0: Setting up contract signer addresses..."
BASE_SIGNER_ADDRESS="0x88ea7374a796c6f31cbfd0f9198b0c473d5ed7ce"  # mock-signer Key 0
QUOTE_SIGNER_ADDRESS="0x6176a61ec3fc1f79358ff241ee835f7143a20b69" # mock-signer Key 1

print_info "Base chain signer address: $BASE_SIGNER_ADDRESS (mock-signer Key 0)"
print_info "Quote chain signer address: $QUOTE_SIGNER_ADDRESS (mock-signer Key 1)"
echo ""

# Deploy factories and read addresses
print_step "Step 0.5: Deploying factory contracts..."

# Check if we're in the infra directory
if [[ ! -f "../infra/justfile" ]]; then
    print_error "This script must be run from the aspens directory"
    print_error "Current directory: $(pwd)"
    exit 1
fi

# Deploy factory on base chain
print_info "Deploying factory on base chain (chain ID: $BASE_SEPOLIA_CHAIN_ID)..."
cd ../infra
if ! just deploy-factory-anvil-1 > /tmp/deploy-factory-base.log 2>&1; then
    print_warn "Factory deployment may have failed, checking for existing deployment..."
fi
cd - > /dev/null

# Read factory address from deployment artifacts or log
if [[ -f "$ARBORTER_DIR/chains/evm/deployment/$BASE_SEPOLIA_CHAIN_ID/Factory/address" ]]; then
    BASE_SEPOLIA_SERVICE_ADDRESS=$(cat "$ARBORTER_DIR/chains/evm/deployment/$BASE_SEPOLIA_CHAIN_ID/Factory/address")
    print_info "Base chain factory address: $BASE_SEPOLIA_SERVICE_ADDRESS"
else
    # Try to extract from deployment log
    BASE_SEPOLIA_SERVICE_ADDRESS=$(grep "Factory deployed at:" /tmp/deploy-factory-base.log | awk '{print $NF}')
    if [[ -z "$BASE_SEPOLIA_SERVICE_ADDRESS" ]]; then
        print_error "Could not find factory address for base chain"
        print_error "Check /tmp/deploy-factory-base.log for details"
        exit 1
    fi
    print_info "Base chain factory address (from log): $BASE_SEPOLIA_SERVICE_ADDRESS"
fi

# Deploy factory on quote chain
print_info "Deploying factory on quote chain (chain ID: $FLARE_COSTON2_CHAIN_ID)..."
cd ../infra
if ! just deploy-factory-anvil-2 > /tmp/deploy-factory-quote.log 2>&1; then
    print_warn "Factory deployment may have failed, checking for existing deployment..."
fi
cd - > /dev/null

# Read factory address from deployment artifacts or log
if [[ -f "$ARBORTER_DIR/chains/evm/deployment/$FLARE_COSTON2_CHAIN_ID/Factory/address" ]]; then
    FLARE_COSTON2_SERVICE_ADDRESS=$(cat "$ARBORTER_DIR/chains/evm/deployment/$FLARE_COSTON2_CHAIN_ID/Factory/address")
    print_info "Quote chain factory address: $FLARE_COSTON2_SERVICE_ADDRESS"
else
    # Try to extract from deployment log
    FLARE_COSTON2_SERVICE_ADDRESS=$(grep "Factory deployed at:" /tmp/deploy-factory-quote.log | awk '{print $NF}')
    if [[ -z "$FLARE_COSTON2_SERVICE_ADDRESS" ]]; then
        print_error "Could not find factory address for quote chain"
        print_error "Check /tmp/deploy-factory-quote.log for details"
        exit 1
    fi
    print_info "Quote chain factory address (from log): $FLARE_COSTON2_SERVICE_ADDRESS"
fi

echo ""

# Check if JWT is already set
if [[ -z "$ASPENS_JWT" ]]; then
    print_step "Step 1: Initializing admin and obtaining JWT..."
    print_warn "No ASPENS_JWT found. Running init-admin..."
    print_warn "If admin already exists, use 'aspens-admin login' instead"
    echo ""

    # Try to login first (in case admin already exists)
    if $ASPENS_ADMIN login 2>/dev/null; then
        print_info "Logged in successfully"
    else
        print_warn "Login failed, attempting to initialize new admin..."
        # Get address from private key - this requires the user to provide it
        print_error "Please run 'aspens-admin init-admin --address <your-address>' manually"
        print_error "Then export ASPENS_JWT and re-run this script"
        exit 1
    fi
else
    print_info "Using existing JWT from ASPENS_JWT environment variable"
fi

echo ""
print_step "Step 2: Setting chains..."

# Set Base Sepolia (using mock-signer Key 0)
print_info "Setting Base Sepolia chain..."
$ASPENS_ADMIN set-chain \
    --architecture "EVM" \
    --canonical-name "Base Sepolia" \
    --network "base-sepolia" \
    --chain-id "$BASE_SEPOLIA_CHAIN_ID" \
    --instance-signer-address "$BASE_SIGNER_ADDRESS" \
    --rpc-url "$BASE_SEPOLIA_RPC_URL" \
    --service-address "$BASE_SEPOLIA_SERVICE_ADDRESS" \
    --permit2-address "$BASE_SEPOLIA_PERMIT2_ADDRESS" \
    --explorer-url "$BASE_SEPOLIA_EXPLORER" \
    || print_warn "Chain may already exist"

# Set Flare Coston2 (using mock-signer Key 1)
print_info "Setting Flare Coston2 chain..."
$ASPENS_ADMIN set-chain \
    --architecture "EVM" \
    --canonical-name "Flare Coston2" \
    --network "flare-coston2" \
    --chain-id "$FLARE_COSTON2_CHAIN_ID" \
    --instance-signer-address "$QUOTE_SIGNER_ADDRESS" \
    --rpc-url "$FLARE_COSTON2_RPC_URL" \
    --service-address "$FLARE_COSTON2_SERVICE_ADDRESS" \
    --permit2-address "$FLARE_COSTON2_PERMIT2_ADDRESS" \
    --explorer-url "$FLARE_COSTON2_EXPLORER" \
    || print_warn "Chain may already exist"

echo ""
print_step "Step 3: Verifying signer public keys..."

# Strip http:// or https:// prefix from URL for grpcurl
GRPC_URL="${ASPENS_MARKET_STACK_URL#http://}"
GRPC_URL="${GRPC_URL#https://}"

# Fetch signer public keys for each chain
SIGNER_RESPONSE=$(grpcurl -plaintext -d '{}' "$GRPC_URL" xyz.aspens.arborter.v1.ArborterService.GetSignerPublicKey 2>&1)
if [[ $? -eq 0 ]]; then
    print_info "Signer public keys from Aspens Market Stack:"
    echo "$SIGNER_RESPONSE" | jq -r '.chainKeys | to_entries[] | "  Chain \(.key): \(.value.publicKey)"' 2>/dev/null || {
        # If jq fails or response is empty, just show raw response
        echo "$SIGNER_RESPONSE"
    }

    # Verify the keys match our expected deterministic addresses
    BASE_CHAIN_ID=$BASE_SEPOLIA_CHAIN_ID
    QUOTE_CHAIN_ID=$FLARE_COSTON2_CHAIN_ID

    # Extract addresses from response if available
    BASE_SIGNER_FROM_ARBORTER=$(echo "$SIGNER_RESPONSE" | jq -r ".chainKeys[\"$BASE_CHAIN_ID\"].publicKey" 2>/dev/null)
    QUOTE_SIGNER_FROM_ARBORTER=$(echo "$SIGNER_RESPONSE" | jq -r ".chainKeys[\"$QUOTE_CHAIN_ID\"].publicKey" 2>/dev/null)

    if [[ "$BASE_SIGNER_FROM_ARBORTER" != "null" && "$BASE_SIGNER_FROM_ARBORTER" != "" ]]; then
        # Compare lowercase versions (Ethereum addresses are case-insensitive)
        BASE_SIGNER_LOWER=$(echo "$BASE_SIGNER_FROM_ARBORTER" | tr '[:upper:]' '[:lower:]')
        BASE_EXPECTED_LOWER=$(echo "$BASE_SIGNER_ADDRESS" | tr '[:upper:]' '[:lower:]')
        if [[ "$BASE_SIGNER_LOWER" == "$BASE_EXPECTED_LOWER" ]]; then
            print_info "✓ Base chain signer matches expected Key 0: $BASE_SIGNER_FROM_ARBORTER"
        else
            print_warn "Base chain signer mismatch!"
            print_warn "  Expected: $BASE_SIGNER_ADDRESS"
            print_warn "  Got: $BASE_SIGNER_FROM_ARBORTER"
        fi
    fi

    if [[ "$QUOTE_SIGNER_FROM_ARBORTER" != "null" && "$QUOTE_SIGNER_FROM_ARBORTER" != "" ]]; then
        # Compare lowercase versions (Ethereum addresses are case-insensitive)
        QUOTE_SIGNER_LOWER=$(echo "$QUOTE_SIGNER_FROM_ARBORTER" | tr '[:upper:]' '[:lower:]')
        QUOTE_EXPECTED_LOWER=$(echo "$QUOTE_SIGNER_ADDRESS" | tr '[:upper:]' '[:lower:]')
        if [[ "$QUOTE_SIGNER_LOWER" == "$QUOTE_EXPECTED_LOWER" ]]; then
            print_info "✓ Quote chain signer matches expected Key 1: $QUOTE_SIGNER_FROM_ARBORTER"
        else
            print_warn "Quote chain signer mismatch!"
            print_warn "  Expected: $QUOTE_SIGNER_ADDRESS"
            print_warn "  Got: $QUOTE_SIGNER_FROM_ARBORTER"
        fi
    fi
else
    print_warn "Could not fetch signer public keys"
    print_warn "Proceeding with deployment using deterministic addresses"
fi

echo ""
print_step "Step 4: Deploying trading contracts..."

# Deploy contract on Base Sepolia
print_info "Deploying trading contract on Base Sepolia..."
$ASPENS_ADMIN deploy-contract "base-sepolia" \
    || print_warn "Contract deployment may have failed or contract already exists"

# Deploy contract on Flare Coston2
print_info "Deploying trading contract on Flare Coston2..."
$ASPENS_ADMIN deploy-contract "flare-coston2" \
    || print_warn "Contract deployment may have failed or contract already exists"

echo ""
print_step "Step 5: Setting tokens..."

# Set USDC on Base Sepolia
print_info "Setting USDC on Base Sepolia..."
$ASPENS_ADMIN set-token \
    --network "base-sepolia" \
    --name "USD Coin" \
    --symbol "USDC" \
    --address "$USDC_ADDRESS_BASE" \
    --decimals 6 \
    --trade-precision 6 \
    || print_warn "Token may already exist"

# Set USDT0 on Flare Coston2
print_info "Setting USDT0 on Flare Coston2..."
$ASPENS_ADMIN set-token \
    --network "flare-coston2" \
    --name "Tether USD" \
    --symbol "USDT0" \
    --address "$USDT0_ADDRESS_FLARE" \
    --decimals 6 \
    --trade-precision 6 \
    || print_warn "Token may already exist"

# Set WC2FLR on Flare Coston2
print_info "Setting WC2FLR on Flare Coston2..."
$ASPENS_ADMIN set-token \
    --network "flare-coston2" \
    --name "Wrapped Coston2 Flare" \
    --symbol "WC2FLR" \
    --address "$WC2FLR_ADDRESS_FLARE" \
    --decimals 18 \
    --trade-precision 6 \
    || print_warn "Token may already exist"

echo ""
print_step "Step 6: Setting markets..."

# Set USDC/USDT0 market (Base Sepolia USDC <-> Flare Coston2 USDT0)
print_info "Setting USDC/USDT0 market..."
$ASPENS_ADMIN set-market \
    --base-network "base-sepolia" \
    --quote-network "flare-coston2" \
    --base-symbol "USDC" \
    --quote-symbol "USDT0" \
    --base-address "$USDC_ADDRESS_BASE" \
    --quote-address "$USDT0_ADDRESS_FLARE" \
    --base-decimals 6 \
    --quote-decimals 6 \
    --pair-decimals 6 \
    || print_warn "Market may already exist"

# Set WC2FLR/USDC market (Flare Coston2 WC2FLR <-> Base Sepolia USDC)
print_info "Setting WC2FLR/USDC market..."
$ASPENS_ADMIN set-market \
    --base-network "flare-coston2" \
    --quote-network "base-sepolia" \
    --base-symbol "WC2FLR" \
    --quote-symbol "USDC" \
    --base-address "$WC2FLR_ADDRESS_FLARE" \
    --quote-address "$USDC_ADDRESS_BASE" \
    --base-decimals 18 \
    --quote-decimals 6 \
    --pair-decimals 6 \
    || print_warn "Market may already exist"

echo ""
print_info "============================================"
print_info "Testnet configuration complete!"
print_info "============================================"
echo ""
print_info "Chains set:"
print_info "  - base-sepolia (Chain ID: $BASE_SEPOLIA_CHAIN_ID)"
print_info "  - flare-coston2 (Chain ID: $FLARE_COSTON2_CHAIN_ID)"
echo ""
print_info "Tokens set:"
print_info "  - USDC on base-sepolia"
print_info "  - USDT0 on flare-coston2"
print_info "  - WC2FLR on flare-coston2"
echo ""
print_info "Markets set:"
print_info "  - USDC/USDT0 (base-sepolia <-> flare-coston2)"
print_info "  - WC2FLR/USDC (flare-coston2 <-> base-sepolia)"
echo ""
print_info "Configuration details:"
print_info "  - Base chain signer (Key 0): $BASE_SIGNER_ADDRESS"
print_info "  - Quote chain signer (Key 1): $QUOTE_SIGNER_ADDRESS"
print_info "  - Trading contracts deployed on both chains"
